### ISSUE TITLE
Schema Validation for AOBJ fails

### ISSUE THREAD

**Issue by schneidermic0** [SAP/abap-file-formats-tools#227]
There is a validation error for AOBJ:

```
> abap-file-formats@0.0.0 generate
> rm -rf generated && node aff.mjs

AOBJ
formats/generate/node_modules/@abaplint/runtime/build/src/types/character.js:38
            this.value = value.get() + "";
                               ^

TypeError: Cannot read properties of null (reading 'get')
    at Character.set (/home/runner/work/abap-file-formats/abap-file-formats/generate/node_modules/@abaplint/runtime/build/src/types/character.js:38:32)
    at SelectDatabase.select (/home/runner/work/abap-file-formats/abap-file-formats/generate/node_modules/@abaplint/runtime/build/src/statements/select.js:31:75)

Node.js v18.14.2
Error: Process completed with exit code 1.
```

Copied from https://github.com/SAP/abap-file-formats/actions/runs/4385938716/jobs/7719410914

See https://github.com/SAP/abap-file-formats/pull/506 and https://github.com/SAP/abap-file-formats/pull/507

**Comment by larshp** [comment]
try merging https://github.com/SAP/abap-file-formats/pull/509

**Comment by schneidermic0** [comment]
This was fast... and it seems to work. I'll close this issue. 👍

Thank you, @larshp.
